# install library

In [54]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

# import library

In [55]:
import pandas as pd
from  sqlalchemy import create_engine

# load dataset

In [56]:
DATABASE_URL = (
"postgresql://postgres.qsbdxqbyrdofksdkolnz:Limamei2000!@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"
)

engine = create_engine(DATABASE_URL)

In [57]:
df.to_sql("hotel_bookings", engine, if_exists="replace", index=False)

390

In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("https://raw.github.com/mexanata/python-dasar/main/hotel_bookings.csv")

In [60]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

# informasi dataset

## data duplikat

In [61]:
df.duplicated().sum()

np.int64(31994)

## info

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

## statistik

In [63]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

## missing value

In [64]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [65]:
df['country'] = df['country'].fillna(df['country'].mode()[0])
df['children'] = df['children'].fillna(df['children'].mode()[0])
df['agent'] = df['agent'].fillna(0)
df['company'] = df['company'].fillna(0)

In [66]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

## data cleaning

In [67]:
#Salin dataset
clean_df = df.copy()

## handle missing value

In [68]:
clean_df['children'] = clean_df['children'].fillna(0)

In [69]:
clean_df['country'] = clean_df['country'].fillna('Unknown')

In [70]:
clean_df['agent'] = clean_df['agent'].fillna(0)

In [71]:
clean_df['company'] = clean_df['company'].fillna(0)

## hapus data duplikat

In [72]:
clean_df.drop_duplicates(inplace=True)

## hapus nilai tidak valid

In [73]:
clean_df = clean_df[clean_df['adr'] >= 0]

clean_df = clean_df[
    clean_df['adults'] >= 0
]

clean_df = clean_df[
    clean_df['children'] >= 0
]

clean_df = clean_df[
    clean_df['babies'] >= 0
]

## ubah tipe data

In [74]:
clean_df['reservation_status_date'] = pd.to_datetime(
    clean_df['reservation_status_date']
)

## rapikan teks

In [75]:
clean_df['hotel'] = clean_df['hotel'].str.strip()

clean_df['meal'] = clean_df['meal'].str.strip()

clean_df['market_segment'] = clean_df['market_segment'].str.strip()

# feature engineering

In [76]:
#total malam menginap
clean_df['total_nights'] = (
    clean_df['stays_in_weekend_nights'] +
    clean_df['stays_in_week_nights']
)

# Total tamu
clean_df['total_guest'] = (
    clean_df['adults'] +
    clean_df['children'] +
    clean_df['babies']
)

## hapus booking tanpa tamu

In [77]:
clean_df = clean_df[
    clean_df['total_guest'] > 0
]

## validasi data setelah cleaning

In [78]:
print("\nMissing Value Setelah Cleaning")
print(clean_df.isnull().sum())

print("\nJumlah Duplikat Setelah Cleaning")
print(clean_df.duplicated().sum())

print("\nStatistik Setelah Cleaning")
print(clean_df.describe())

Missing Value Setelah Cleaning
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
total_nights                      0
total_guest                       0
dtype: int64

Jumlah Duplikat Setelah Cleaning
0

Statistik Setelah Cleaning
        is_canceled     lead_time  arrival_date_year  \
count  87210.000000  87210.000000       87210.000000
mean       0.275290     79.984233        2016.210320
min        0.000000      0.000000        2015.000000
25%        0.000000     11.000000        2016.000000
50%        0.000000     49.000000        2016.000000
75%        1.000000    125.000000        2017.000000
max        1.000000    737.000000        2017.000000
std        0.446663     86.061487           0.686084

       arrival_date_week_number  arrival_date_day_of_month  \
count              87210.000000               87210.000000
mean                  26.837060                  15.815617
min                    1.000000                   1.000000
25%                   16.000000                   8.000000
50%                   27.000000                  16.000000
75%                   37.000000                  23.000000
max                   53.000000                  31.000000
std                   13.668025                   8.835117

       stays_in_weekend_nights  stays_in_week_nights        adults  \
count             87210.000000          87210.000000  87210.000000
mean                  1.004701              2.624137      1.879475
min                   0.000000              0.000000      0.000000
25%                   0.000000              1.000000      2.000000
50%                   1.000000              2.000000      2.000000
75%                   2.000000              4.000000      2.000000
max                  19.000000             50.000000     55.000000
std                   1.027403              2.039909      0.621709

           children        babies  ...  booking_changes         agent  \
count  87210.000000  87210.000000  ...     87210.000000  87210.000000
mean       0.138929      0.010847  ...         0.268524     81.090081
min        0.000000      0.000000  ...         0.000000      0.000000
25%        0.000000      0.000000  ...         0.000000      9.000000
50%        0.000000      0.000000  ...         0.000000      9.000000
75%        0.000000      0.000000  ...         0.000000    240.000000
max       10.000000     10.000000  ...        18.000000    535.000000
std        0.456312      0.113717  ...         0.710675    109.970661

            company  days_in_waiting_list           adr  \
count  87210.000000          87210.000000  87210.000000
mean      10.977594              0.746463    106.527244
min        0.000000              0.000000      0.000000
25%        0.000000              0.000000     72.250000
50%        0.000000              0.000000     98.250000
75%        0.000000              0.000000    134.100000
max      543.000000            391.000000   5400.000000
std       53.933926             10.002141     54.881284

       required_car_parking_spaces  total_of_special_requests  \
count                 87210.000000               87210.000000
mean                      0.084325                   0.698991
min                       0.000000                   0.000000
25%                       0.000000                   0.000000
50%                       0.000000                   0.000000
75%                       0.000000                   1.000000
max                       8.000000                   5.000000
std                       0.281688                   0.832049

             reservation_status_date  total_nights   total_guest
count                          87210  87210.000000  87210.000000
mean   2016-08-31 02:53:20.495356160      3.628838      2.029251
min              2014-10-17 00:00:00      0.000000      1.000000
25%              2016-03-18 00:00:00      2.000000      2.000000
50%              2016-09-08 00:00:00      3.000000      2.000000
75%              2017-03-05 00:00:00      5.000000      2.000000
max              2017-09-14 00:00:00     69.000000     55.000000
std                              NaN      2.742996      0.790140

[8 rows x 23 columns]

# koneksi db supabase/postgresql

In [79]:
DATABASE_URL = (
"postgresql://postgres.qsbdxqbyrdofksdkolnz:Limamei2000!@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"
)

engine = create_engine(DATABASE_URL)

# simpan data ke db

In [80]:
clean_df.to_sql(
    'hotel_bookings',
    engine,
    if_exists='replace',
    index=False
)

print("\nData berhasil disimpan ke PostgreSQL")

Data berhasil disimpan ke PostgreSQL

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         119390 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           119390 non-null  float64
 24  company                         119390 non-null  float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB